[package]
name = "fork-observer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bitcoincore-rpc = { git = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc", branch = "master" }
warp = "0.3"
serde = "1.0.127"
toml = "0.5"

log = { version = "0.4.17" }
env_logger = { version = "0.9.0" }
hex = { version = "0.4" }
rusqlite = { version = "0.27.0", features = ["bundled"] }
reqwest = { version = "0.11" }
tokio = { version = "1", features = ["full"] }
petgraph = { version = "0.6.2" }
