//! The activity log: a timestamped, per-node log of chain-tip changes, reorgs,
//! reachability changes and similar events (issue #27).
//!
//! Events are generated by diffing consecutive `getchaintips` results (and the
//! other node state transitions) in the per-node task in `main.rs`, sent
//! through an mpsc channel to a single writer task, and stored in a SQLite
//! database that is separate from the headers database. The most recent events
//! per network are additionally kept in an in-memory ring buffer so the common
//! "show me recent activity" API request never hits the database.

use std::collections::{BTreeMap, HashMap, VecDeque};
use std::path::Path;
use std::str::FromStr;
use std::sync::Arc;
use std::time::SystemTime;

use corepc_client::bitcoin::BlockHash;
use log::{debug, error, info, warn};
use petgraph::graph::NodeIndex;
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc::UnboundedReceiver;
use tokio::sync::Mutex;
use tokio::time::Duration;

use crate::error::DbError;
use crate::types::{ChainTip, ChainTipStatus, Tree};

/// Number of recent events kept in memory per network.
pub const RING_BUFFER_SIZE: usize = 250;
/// Number of events the activity API serves per request. Pagination is by
/// `?before=<id>`, so this is fixed rather than something a request can pick.
pub const EVENTS_PER_PAGE: usize = 100;
/// A node is considered lagging once its active tip is at least this many
/// blocks behind the best active tip of the network's nodes.
pub const LAG_ENTER: u64 = 3;
/// A lagging node is considered caught-up again once its active tip is at
/// most this many blocks behind. Having this lower than [`LAG_ENTER`] adds
/// hysteresis so a node hovering around the threshold doesn't produce a
/// lagging/caught-up event pair per block.
pub const LAG_EXIT: u64 = 1;
/// How often the retention task archives and purges old events.
pub const RETENTION_INTERVAL: Duration = Duration::from_secs(6 * 60 * 60);

const CREATE_STMT_TABLE_ACTIVITY: &str = "
CREATE TABLE IF NOT EXISTS activity (
    id        INTEGER PRIMARY KEY,
    timestamp INTEGER NOT NULL,
    network   INTEGER NOT NULL,
    node      INTEGER,
    kind      TEXT NOT NULL,
    details   TEXT NOT NULL
)
";

const CREATE_STMT_INDEX_ACTIVITY: &str = "
CREATE INDEX IF NOT EXISTS activity_network_ts_idx ON activity (network, timestamp)
";

// The archive files use the same schema as the live database, so they can be
// queried (or re-attached) with the same tooling.
const CREATE_STMT_TABLE_ARCHIVE: &str = "
CREATE TABLE IF NOT EXISTS archive.activity (
    id        INTEGER PRIMARY KEY,
    timestamp INTEGER NOT NULL,
    network   INTEGER NOT NULL,
    node      INTEGER,
    kind      TEXT NOT NULL,
    details   TEXT NOT NULL
)
";

const SELECT_STMT_EVENTS_BEFORE: &str = "
SELECT
    id, timestamp, node, kind, details
FROM
    activity
WHERE
    network = ?1 AND id < ?2
ORDER BY
    id DESC
LIMIT ?3
";

pub type ActivityDb = Arc<Mutex<Connection>>;
/// Per-network ring buffers of recent events, oldest at the front.
pub type ActivityRingBuffers = Arc<Mutex<BTreeMap<u32, VecDeque<ActivityEventJson>>>>;

/// What a node did, as recorded in the activity log. Serialized adjacently
/// tagged so the `kind` string and the `details` object land in separate
/// database columns and API fields.
#[derive(Debug, Clone, Serialize, PartialEq)]
#[serde(tag = "kind", content = "details", rename_all = "kebab-case")]
pub enum ActivityEventKind {
    /// The node's active tip moved to a descendant block (a normal advance,
    /// by one or more blocks).
    ActiveTipChanged {
        old_hash: String,
        old_height: u64,
        new_hash: String,
        new_height: u64,
    },
    /// The node's active tip moved to a block that is NOT a descendant of the
    /// previous active tip. Emitted instead of `ActiveTipChanged`. `depth` is
    /// the number of blocks abandoned (old height - common ancestor height).
    ReorgDetected {
        old_hash: String,
        old_height: u64,
        new_hash: String,
        new_height: u64,
        common_ancestor: String,
        common_height: u64,
        depth: u64,
    },
    /// A (non-active) tip the node didn't report before: a fork, stale,
    /// headers-only, or invalid branch appeared.
    TipAdded {
        hash: String,
        height: u64,
        status: String,
    },
    /// A tip the node already reported changed status, e.g. an active tip
    /// that became a valid-fork after a reorg, or a valid-fork that was
    /// found to be invalid.
    TipStatusChanged {
        hash: String,
        height: u64,
        old_status: String,
        new_status: String,
    },
    /// A tip appeared as or transitioned to status `invalid`. Emitted in
    /// addition to `TipAdded`/`TipStatusChanged` so invalid blocks can be
    /// queried directly by kind.
    InvalidBlockObserved { hash: String, height: u64 },
    /// A request to the node failed after it was previously reachable.
    NodeUnreachable {},
    /// The node responded again after being unreachable.
    NodeReachable {},
    /// The node's active tip fell at least [`LAG_ENTER`] blocks behind the
    /// best active tip among the network's nodes.
    NodeLagging { node_height: u64, best_height: u64 },
    /// A previously lagging node is within [`LAG_EXIT`] blocks of the best
    /// active tip again.
    NodeCaughtUp { node_height: u64, best_height: u64 },
}

impl ActivityEventKind {
    /// Splits the event into the `kind` tag and the `details` JSON object,
    /// as stored in the database and served by the API.
    pub fn kind_and_details(&self) -> (String, serde_json::Value) {
        let value = serde_json::to_value(self).expect("activity events are always serializable");
        let kind = value["kind"]
            .as_str()
            .expect("adjacently tagged serialization always has a kind")
            .to_string();
        let details = value
            .get("details")
            .cloned()
            .unwrap_or_else(|| serde_json::json!({}));
        (kind, details)
    }
}

/// One activity log entry as produced by the event generation sites. All
/// events are currently node-scoped.
#[derive(Debug, Clone, PartialEq)]
pub struct ActivityEvent {
    pub timestamp: u64,
    pub network_id: u32,
    pub node_id: u32,
    pub kind: ActivityEventKind,
}

impl ActivityEvent {
    pub fn new(network_id: u32, node_id: u32, kind: ActivityEventKind) -> Self {
        ActivityEvent {
            timestamp: unix_time_now(),
            network_id,
            node_id,
            kind,
        }
    }
}

/// An activity log entry as stored in the database, the ring buffers, and
/// served by the API.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct ActivityEventJson {
    /// Database row id; monotonically increasing and used as the pagination
    /// cursor (`?before=<id>`).
    pub id: i64,
    pub timestamp: u64,
    pub node_id: Option<u32>,
    pub kind: String,
    pub details: serde_json::Value,
}

#[derive(Serialize)]
pub struct ActivityJsonResponse {
    pub events: Vec<ActivityEventJson>,
}

/// Query parameters of the activity API.
#[derive(Deserialize)]
pub struct ActivityQuery {
    pub before: Option<i64>,
}

/// Handle to the activity log: the (separate) database and the per-network
/// in-memory ring buffers of recent events.
#[derive(Clone)]
pub struct Activity {
    pub db: ActivityDb,
    pub cache: ActivityRingBuffers,
}

impl Activity {
    pub fn new(connection: Connection) -> Self {
        Activity {
            db: Arc::new(Mutex::new(connection)),
            cache: Arc::new(Mutex::new(BTreeMap::new())),
        }
    }

    /// Sets up the schema and switches the database to WAL mode.
    pub async fn setup(&self) -> Result<(), DbError> {
        let db = self.db.lock().await;
        // `PRAGMA journal_mode` returns the new mode as a row.
        db.query_row("PRAGMA journal_mode=WAL", [], |_| Ok(()))?;
        db.execute(CREATE_STMT_TABLE_ACTIVITY, [])?;
        db.execute(CREATE_STMT_INDEX_ACTIVITY, [])?;
        Ok(())
    }

    /// Fills the per-network ring buffers with the most recent events from
    /// the database, so recent activity survives a restart.
    pub async fn preload_cache(&self, network_ids: &[u32]) -> Result<(), DbError> {
        let mut buffers: BTreeMap<u32, VecDeque<ActivityEventJson>> = BTreeMap::new();
        {
            let db = self.db.lock().await;
            for network_id in network_ids {
                // Newest first from the database, reversed into the buffer so
                // the newest event sits at the back.
                let events = query_events(&db, *network_id, i64::MAX, RING_BUFFER_SIZE)?;
                buffers.insert(*network_id, events.into_iter().rev().collect());
            }
        }
        let mut cache = self.cache.lock().await;
        for (network_id, buffer) in buffers {
            info!(
                "preloaded {} recent activity events for network {}",
                buffer.len(),
                network_id
            );
            cache.insert(network_id, buffer);
        }
        Ok(())
    }

    /// The most recent events of a network (newest first), served from the
    /// in-memory ring buffer.
    pub async fn recent_events(&self, network_id: u32, count: usize) -> Vec<ActivityEventJson> {
        let cache = self.cache.lock().await;
        match cache.get(&network_id) {
            Some(buffer) => buffer.iter().rev().take(count).cloned().collect(),
            None => vec![],
        }
    }

    /// Events of a network older than the `before` row id (newest first),
    /// from the database. Used for paginating past the ring buffer.
    pub async fn events_before(
        &self,
        network_id: u32,
        before: i64,
        count: usize,
    ) -> Result<Vec<ActivityEventJson>, DbError> {
        let db = self.db.lock().await;
        query_events(&db, network_id, before, count)
    }
}

fn query_events(
    connection: &Connection,
    network_id: u32,
    before: i64,
    limit: usize,
) -> Result<Vec<ActivityEventJson>, DbError> {
    let mut stmt = connection.prepare(SELECT_STMT_EVENTS_BEFORE)?;
    let mut rows = stmt.query(params![network_id, before, limit as i64])?;
    let mut events = vec![];
    while let Some(row) = rows.next()? {
        let details: String = row.get(4)?;
        events.push(ActivityEventJson {
            id: row.get(0)?,
            timestamp: row.get::<_, i64>(1)? as u64,
            node_id: row.get::<_, Option<i64>>(2)?.map(|id| id as u32),
            kind: row.get(3)?,
            // The details were serialized by us, so this only fails if the
            // database was edited externally. Degrade to a JSON string.
            details: serde_json::from_str(&details).unwrap_or(serde_json::Value::String(details)),
        });
    }
    Ok(events)
}

/// Receives events from the generation sites and persists them: insert into
/// the database, then append to the in-memory ring buffers. Runs until all
/// senders are dropped.
pub async fn run_activity_writer(activity: Activity, mut rx: UnboundedReceiver<ActivityEvent>) {
    let limit = 100;
    let mut buffer: Vec<ActivityEvent> = Vec::with_capacity(limit);
    loop {
        buffer.clear();
        if rx.recv_many(&mut buffer, limit).await == 0 {
            debug!("all activity event senders are gone, stopping the activity writer");
            return;
        }
        if let Err(e) = write_events(&activity, &buffer).await {
            error!("could not write activity events to the database: {}", e);
        }
    }
}

pub(crate) async fn write_events(
    activity: &Activity,
    events: &[ActivityEvent],
) -> Result<(), DbError> {
    let mut written: Vec<(u32, ActivityEventJson)> = Vec::with_capacity(events.len());
    {
        let mut db = activity.db.lock().await;
        let tx = db.transaction()?;
        for event in events {
            let (kind_str, details) = event.kind.kind_and_details();
            tx.execute(
                "INSERT INTO activity (timestamp, network, node, kind, details)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                params![
                    event.timestamp as i64,
                    event.network_id,
                    event.node_id,
                    kind_str,
                    details.to_string(),
                ],
            )?;
            written.push((
                event.network_id,
                ActivityEventJson {
                    id: tx.last_insert_rowid(),
                    timestamp: event.timestamp,
                    node_id: Some(event.node_id),
                    kind: kind_str,
                    details,
                },
            ));
        }
        tx.commit()?;
    }

    let mut cache = activity.cache.lock().await;
    for (network_id, event) in written {
        let buffer = cache.entry(network_id).or_default();
        buffer.push_back(event);
        while buffer.len() > RING_BUFFER_SIZE {
            buffer.pop_front();
        }
    }
    Ok(())
}

/// Diffs two (sorted) `getchaintips` results of a node into activity events.
///
/// An empty `old` yields no events: it's the first successful poll after
/// startup and diffing against it would log every historical fork tip the
/// node knows about.
pub fn diff_tips(old: &[ChainTip], new: &[ChainTip]) -> Vec<ActivityEventKind> {
    if old.is_empty() {
        return vec![];
    }
    let mut events = vec![];

    let old_active = old.iter().find(|t| t.status == ChainTipStatus::Active);
    let new_active = new.iter().find(|t| t.status == ChainTipStatus::Active);
    if let (Some(old_active), Some(new_active)) = (old_active, new_active) {
        if old_active.hash != new_active.hash {
            events.push(ActivityEventKind::ActiveTipChanged {
                old_hash: old_active.hash.clone(),
                old_height: old_active.height,
                new_hash: new_active.hash.clone(),
                new_height: new_active.height,
            });
        }
    }

    for tip in new {
        match old.iter().find(|o| o.hash == tip.hash) {
            None => {
                // A new active tip is already covered by ActiveTipChanged.
                if tip.status != ChainTipStatus::Active {
                    events.push(ActivityEventKind::TipAdded {
                        hash: tip.hash.clone(),
                        height: tip.height,
                        status: tip.status.to_string(),
                    });
                }
                if tip.status == ChainTipStatus::Invalid {
                    events.push(ActivityEventKind::InvalidBlockObserved {
                        hash: tip.hash.clone(),
                        height: tip.height,
                    });
                }
            }
            Some(old_tip) if old_tip.status != tip.status => {
                // The tip becoming active is covered by ActiveTipChanged.
                if tip.status != ChainTipStatus::Active {
                    events.push(ActivityEventKind::TipStatusChanged {
                        hash: tip.hash.clone(),
                        height: tip.height,
                        old_status: old_tip.status.to_string(),
                        new_status: tip.status.to_string(),
                    });
                }
                if tip.status == ChainTipStatus::Invalid {
                    events.push(ActivityEventKind::InvalidBlockObserved {
                        hash: tip.hash.clone(),
                        height: tip.height,
                    });
                }
            }
            Some(_) => (),
        }
    }
    events
}

/// Checks whether an active-tip change was a reorg: `Some((common ancestor
/// hash, common ancestor height, depth))` if the old tip is not an ancestor
/// of the new tip, `None` for a normal advance or when either block is not
/// in the header tree.
pub async fn reorg_info(tree: &Tree, old_hash: &str, new_hash: &str) -> Option<(String, u64, u64)> {
    let old_block_hash = BlockHash::from_str(old_hash).ok()?;
    let new_block_hash = BlockHash::from_str(new_hash).ok()?;

    let tree_locked = tree.lock().await;
    let (graph, index) = (&tree_locked.0, &tree_locked.1);
    let old_idx = *index.get(&old_block_hash)?;
    let new_idx = *index.get(&new_block_hash)?;

    // All ancestors of the old tip (including itself). Each block has at most
    // one incoming edge (its parent).
    let mut old_chain: HashMap<NodeIndex, u64> = HashMap::new();
    let mut current = Some(old_idx);
    while let Some(idx) = current {
        old_chain.insert(idx, graph[idx].height);
        current = graph
            .neighbors_directed(idx, petgraph::Direction::Incoming)
            .next();
    }

    // Walk back from the new tip until we hit the old tip's chain.
    let mut current = Some(new_idx);
    while let Some(idx) = current {
        if old_chain.contains_key(&idx) {
            if idx == old_idx {
                // The old tip is an ancestor of the new tip: a normal advance.
                return None;
            }
            let ancestor = &graph[idx];
            let depth = graph[old_idx].height.saturating_sub(ancestor.height);
            return Some((
                ancestor.header.block_hash().to_string(),
                ancestor.height,
                depth,
            ));
        }
        current = graph
            .neighbors_directed(idx, petgraph::Direction::Incoming)
            .next();
    }
    // No common ancestor in the (pruned) tree: we can't tell more than "the
    // tip changed".
    None
}

/// Diffs a node's tips and upgrades active-tip changes to reorg events where
/// the header tree shows the old tip was abandoned.
pub async fn tip_events(old: &[ChainTip], new: &[ChainTip], tree: &Tree) -> Vec<ActivityEventKind> {
    let mut events = diff_tips(old, new);
    for event in events.iter_mut() {
        if let ActivityEventKind::ActiveTipChanged {
            old_hash,
            old_height,
            new_hash,
            new_height,
        } = event
        {
            if let Some((common_ancestor, common_height, depth)) =
                reorg_info(tree, old_hash, new_hash).await
            {
                *event = ActivityEventKind::ReorgDetected {
                    old_hash: old_hash.clone(),
                    old_height: *old_height,
                    new_hash: new_hash.clone(),
                    new_height: *new_height,
                    common_ancestor,
                    common_height,
                    depth,
                };
            }
        }
    }
    events
}

/// Derives lagging/caught-up transitions from the active tip heights of a
/// network's nodes. `state` keeps the currently-lagging flags between calls
/// (hysteresis: enter at [`LAG_ENTER`] behind, exit at [`LAG_EXIT`]). Nodes
/// without an active tip yet are absent from `heights` and skipped.
pub fn lagging_events(
    heights: &BTreeMap<u32, u64>,
    state: &mut BTreeMap<u32, bool>,
) -> Vec<(u32, ActivityEventKind)> {
    let best_height = match heights.values().max() {
        Some(best) => *best,
        None => return vec![],
    };
    let mut events = vec![];
    for (node_id, height) in heights {
        let behind = best_height.saturating_sub(*height);
        let lagging = state.entry(*node_id).or_insert(false);
        if !*lagging && behind >= LAG_ENTER {
            *lagging = true;
            events.push((
                *node_id,
                ActivityEventKind::NodeLagging {
                    node_height: *height,
                    best_height,
                },
            ));
        } else if *lagging && behind <= LAG_EXIT {
            *lagging = false;
            events.push((
                *node_id,
                ActivityEventKind::NodeCaughtUp {
                    node_height: *height,
                    best_height,
                },
            ));
        }
    }
    events
}

/// Moves all events of `network_id` older than `cutoff` (unix seconds) into
/// the archive file of the current month, then deletes them from the live
/// database — both in one transaction, so no event is ever in limbo. Returns
/// the number of archived events.
pub async fn archive_and_purge(
    db: &ActivityDb,
    archive_dir: &Path,
    network_id: u32,
    cutoff: u64,
) -> Result<u64, DbError> {
    let mut db_locked = db.lock().await;

    // Don't create (empty) archive files when there is nothing to archive.
    let expiring: i64 = db_locked.query_row(
        "SELECT COUNT(*) FROM activity WHERE network = ?1 AND timestamp < ?2",
        params![network_id, cutoff as i64],
        |row| row.get(0),
    )?;
    if expiring == 0 {
        return Ok(0);
    }

    if let Err(e) = std::fs::create_dir_all(archive_dir) {
        warn!(
            "could not create the activity archive directory {:?}: {}",
            archive_dir, e
        );
        return Err(DbError::Rusqlite(rusqlite::Error::InvalidPath(
            archive_dir.to_path_buf(),
        )));
    }
    let archive_path = archive_dir.join(format!(
        "activity-archive-{}.sqlite",
        year_month(unix_time_now())
    ));

    // ATTACH/DETACH can't run inside a transaction.
    db_locked.execute(
        "ATTACH DATABASE ?1 AS archive",
        [archive_path.to_string_lossy()],
    )?;
    let result = (|| -> Result<u64, DbError> {
        db_locked.execute(CREATE_STMT_TABLE_ARCHIVE, [])?;
        let tx = db_locked.transaction()?;
        let moved = tx.execute(
            "INSERT INTO archive.activity
             SELECT id, timestamp, network, node, kind, details FROM activity
             WHERE network = ?1 AND timestamp < ?2",
            params![network_id, cutoff as i64],
        )?;
        tx.execute(
            "DELETE FROM activity WHERE network = ?1 AND timestamp < ?2",
            params![network_id, cutoff as i64],
        )?;
        tx.commit()?;
        Ok(moved as u64)
    })();
    // Detach even if archiving failed (the failed transaction rolled back).
    if let Err(e) = db_locked.execute("DETACH DATABASE archive", []) {
        warn!("could not detach the activity archive database: {}", e);
    }
    result
}

/// Periodically archives and purges events older than each network's
/// retention. `retentions` holds `(network id, retention in days)` pairs.
pub async fn run_retention(
    activity: Activity,
    archive_dir: std::path::PathBuf,
    retentions: Vec<(u32, u64)>,
) {
    let mut interval = tokio::time::interval(RETENTION_INTERVAL);
    loop {
        // The first tick is immediate: archive on startup, then every interval.
        interval.tick().await;
        for (network_id, days) in retentions.iter() {
            let cutoff = unix_time_now().saturating_sub(days * 24 * 60 * 60);
            match archive_and_purge(&activity.db, &archive_dir, *network_id, cutoff).await {
                Ok(0) => debug!(
                    "no activity events of network {} older than {} days to archive",
                    network_id, days
                ),
                Ok(moved) => info!(
                    "archived and purged {} activity events of network {} older than {} days",
                    moved, network_id, days
                ),
                Err(e) => error!(
                    "could not archive activity events of network {}: {}",
                    network_id, e
                ),
            }
        }
    }
}

pub fn unix_time_now() -> u64 {
    match SystemTime::now().duration_since(SystemTime::UNIX_EPOCH) {
        Ok(n) => n.as_secs(),
        Err(_) => {
            warn!("SystemTime is before UNIX_EPOCH. Using 0 as activity timestamp.");
            0u64
        }
    }
}

/// The `YYYY-MM` of a unix timestamp (UTC), used to name archive files.
/// Days-to-civil algorithm by Howard Hinnant; avoids a date-time dependency.
fn year_month(unix_ts: u64) -> String {
    let days = (unix_ts / 86400) as i64;
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = (z - era * 146097) as u64; // day of era
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365; // year of era
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // day of year (Mar 1 based)
    let mp = (5 * doy + 2) / 153;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let mut year = yoe as i64 + era * 400;
    if month <= 2 {
        year += 1;
    }
    format!("{:04}-{:02}", year, month)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{HeaderInfo, TreeInfo};
    use corepc_client::bitcoin::blockdata::block::{Header, Version};
    use corepc_client::bitcoin::hashes::Hash;
    use corepc_client::bitcoin::{CompactTarget, TxMerkleNode};
    use petgraph::graph::DiGraph;

    fn tip(hash: &str, height: u64, status: ChainTipStatus) -> ChainTip {
        ChainTip {
            height,
            hash: hash.to_string(),
            branchlen: 0,
            status,
        }
    }

    #[test]
    fn diff_tips_first_poll_yields_no_events() {
        let new = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 8, ChainTipStatus::ValidFork),
            tip("cc", 5, ChainTipStatus::Invalid),
        ];
        assert!(diff_tips(&[], &new).is_empty());
    }

    #[test]
    fn diff_tips_unchanged_yields_no_events() {
        let tips = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 8, ChainTipStatus::ValidFork),
        ];
        assert!(diff_tips(&tips, &tips).is_empty());
    }

    #[test]
    fn diff_tips_active_advance() {
        let old = vec![tip("aa", 10, ChainTipStatus::Active)];
        let new = vec![tip("bb", 11, ChainTipStatus::Active)];
        assert_eq!(
            diff_tips(&old, &new),
            vec![ActivityEventKind::ActiveTipChanged {
                old_hash: "aa".to_string(),
                old_height: 10,
                new_hash: "bb".to_string(),
                new_height: 11,
            }]
        );
    }

    #[test]
    fn diff_tips_new_fork_tip() {
        let old = vec![tip("aa", 10, ChainTipStatus::Active)];
        let new = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 9, ChainTipStatus::ValidFork),
        ];
        assert_eq!(
            diff_tips(&old, &new),
            vec![ActivityEventKind::TipAdded {
                hash: "bb".to_string(),
                height: 9,
                status: "valid-fork".to_string(),
            }]
        );
    }

    #[test]
    fn diff_tips_new_invalid_tip_yields_both_events() {
        let old = vec![tip("aa", 10, ChainTipStatus::Active)];
        let new = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 11, ChainTipStatus::Invalid),
        ];
        assert_eq!(
            diff_tips(&old, &new),
            vec![
                ActivityEventKind::TipAdded {
                    hash: "bb".to_string(),
                    height: 11,
                    status: "invalid".to_string(),
                },
                ActivityEventKind::InvalidBlockObserved {
                    hash: "bb".to_string(),
                    height: 11,
                }
            ]
        );
    }

    #[test]
    fn diff_tips_status_change_to_invalid() {
        let old = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 11, ChainTipStatus::HeadersOnly),
        ];
        let new = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 11, ChainTipStatus::Invalid),
        ];
        assert_eq!(
            diff_tips(&old, &new),
            vec![
                ActivityEventKind::TipStatusChanged {
                    hash: "bb".to_string(),
                    height: 11,
                    old_status: "headers-only".to_string(),
                    new_status: "invalid".to_string(),
                },
                ActivityEventKind::InvalidBlockObserved {
                    hash: "bb".to_string(),
                    height: 11,
                }
            ]
        );
    }

    #[test]
    fn diff_tips_reorg_logs_active_change_and_old_tip_status() {
        // A reorg as seen via getchaintips: the fork tip becomes active and
        // the old active tip stays behind as a valid-fork.
        let old = vec![
            tip("aa", 10, ChainTipStatus::Active),
            tip("bb", 10, ChainTipStatus::ValidFork),
        ];
        let new = vec![
            tip("cc", 11, ChainTipStatus::Active),
            tip("aa", 10, ChainTipStatus::ValidFork),
        ];
        assert_eq!(
            diff_tips(&old, &new),
            vec![
                ActivityEventKind::ActiveTipChanged {
                    old_hash: "aa".to_string(),
                    old_height: 10,
                    new_hash: "cc".to_string(),
                    new_height: 11,
                },
                ActivityEventKind::TipStatusChanged {
                    hash: "aa".to_string(),
                    height: 10,
                    old_status: "active".to_string(),
                    new_status: "valid-fork".to_string(),
                },
            ]
        );
    }

    // --- reorg_info ---

    fn header(prev: BlockHash, nonce: u32) -> Header {
        Header {
            version: Version::from_consensus(0x2000_0000),
            prev_blockhash: prev,
            merkle_root: TxMerkleNode::all_zeros(),
            time: 1_600_000_000,
            bits: CompactTarget::from_consensus(0x207f_ffff),
            nonce,
        }
    }

    fn hi(height: u64, header: Header) -> HeaderInfo {
        HeaderInfo {
            height,
            header: header.into(),
            miner: String::new(),
        }
    }

    fn tree_from(headers: &[HeaderInfo]) -> Tree {
        let mut graph: DiGraph<HeaderInfo, bool> = DiGraph::new();
        let mut index: HashMap<BlockHash, NodeIndex> = HashMap::new();
        for h in headers {
            let idx = graph.add_node(h.clone());
            index.insert(h.header.block_hash(), idx);
        }
        for h in headers {
            let current = index[&h.header.block_hash()];
            if let Some(prev) = index.get(&h.header.prev_blockhash) {
                graph.update_edge(*prev, current, false);
            }
        }
        let tree_info: TreeInfo = (graph, index);
        Arc::new(Mutex::new(tree_info))
    }

    // root(0) -> a(1) -> b(2) -> c(3)
    //                \-> d(2) -> e(3)
    fn forked_chain() -> (Tree, Vec<HeaderInfo>) {
        let root = hi(0, header(BlockHash::all_zeros(), 0));
        let a = hi(1, header(root.header.block_hash(), 1));
        let b = hi(2, header(a.header.block_hash(), 2));
        let c = hi(3, header(b.header.block_hash(), 3));
        let d = hi(2, header(a.header.block_hash(), 4));
        let e = hi(3, header(d.header.block_hash(), 5));
        let headers = vec![root, a, b, c, d, e];
        (tree_from(&headers), headers)
    }

    #[tokio::test]
    async fn reorg_info_normal_advance_is_none() {
        let (tree, headers) = forked_chain();
        let b = &headers[2];
        let c = &headers[3];
        assert_eq!(
            reorg_info(
                &tree,
                &b.header.block_hash().to_string(),
                &c.header.block_hash().to_string(),
            )
            .await,
            None
        );
    }

    #[tokio::test]
    async fn reorg_info_detects_depth_and_ancestor() {
        let (tree, headers) = forked_chain();
        let a = &headers[1];
        let b = &headers[2];
        let c = &headers[3];
        let e = &headers[5];

        // Tip moves from c (height 3) to e (height 3, other branch): the
        // common ancestor is a (height 1), two blocks (b, c) are abandoned.
        assert_eq!(
            reorg_info(
                &tree,
                &c.header.block_hash().to_string(),
                &e.header.block_hash().to_string(),
            )
            .await,
            Some((a.header.block_hash().to_string(), 1, 2))
        );

        // Tip moves from b (height 2) to e: one block abandoned.
        assert_eq!(
            reorg_info(
                &tree,
                &b.header.block_hash().to_string(),
                &e.header.block_hash().to_string(),
            )
            .await,
            Some((a.header.block_hash().to_string(), 1, 1))
        );
    }

    #[tokio::test]
    async fn reorg_info_unknown_block_is_none() {
        let (tree, headers) = forked_chain();
        let c = &headers[3];
        let unknown = "00".repeat(32);
        assert_eq!(
            reorg_info(&tree, &unknown, &c.header.block_hash().to_string()).await,
            None
        );
        assert_eq!(
            reorg_info(&tree, &c.header.block_hash().to_string(), &unknown).await,
            None
        );
    }

    #[tokio::test]
    async fn tip_events_upgrades_to_reorg() {
        let (tree, headers) = forked_chain();
        let c = &headers[3];
        let e = &headers[5];
        let old = vec![tip(
            &c.header.block_hash().to_string(),
            3,
            ChainTipStatus::Active,
        )];
        let new = vec![
            tip(
                &e.header.block_hash().to_string(),
                3,
                ChainTipStatus::Active,
            ),
            tip(
                &c.header.block_hash().to_string(),
                3,
                ChainTipStatus::ValidFork,
            ),
        ];
        let events = tip_events(&old, &new, &tree).await;
        assert!(matches!(
            events[0],
            ActivityEventKind::ReorgDetected { depth: 2, .. }
        ));
    }

    // --- lagging ---

    #[test]
    fn lagging_enter_exit_with_hysteresis() {
        let mut state: BTreeMap<u32, bool> = BTreeMap::new();

        // Node 1 is 3 behind: lagging.
        let heights: BTreeMap<u32, u64> = [(0, 103), (1, 100)].iter().copied().collect();
        let events = lagging_events(&heights, &mut state);
        assert_eq!(
            events,
            vec![(
                1,
                ActivityEventKind::NodeLagging {
                    node_height: 100,
                    best_height: 103
                }
            )]
        );

        // Still 2 behind: within hysteresis, no event.
        let heights: BTreeMap<u32, u64> = [(0, 103), (1, 101)].iter().copied().collect();
        assert!(lagging_events(&heights, &mut state).is_empty());

        // 1 behind: caught up.
        let heights: BTreeMap<u32, u64> = [(0, 103), (1, 102)].iter().copied().collect();
        let events = lagging_events(&heights, &mut state);
        assert_eq!(
            events,
            vec![(
                1,
                ActivityEventKind::NodeCaughtUp {
                    node_height: 102,
                    best_height: 103
                }
            )]
        );

        // 2 behind again: no re-entry below the enter threshold.
        let heights: BTreeMap<u32, u64> = [(0, 104), (1, 102)].iter().copied().collect();
        assert!(lagging_events(&heights, &mut state).is_empty());
    }

    #[test]
    fn lagging_single_node_never_lags() {
        let mut state: BTreeMap<u32, bool> = BTreeMap::new();
        let heights: BTreeMap<u32, u64> = [(0, 100)].iter().copied().collect();
        assert!(lagging_events(&heights, &mut state).is_empty());
        assert!(lagging_events(&BTreeMap::new(), &mut state).is_empty());
    }

    // --- database ---

    async fn test_activity() -> Activity {
        let activity = Activity::new(Connection::open_in_memory().expect("in-memory db"));
        activity.setup().await.expect("setup");
        activity
    }

    fn event(network_id: u32, node_id: u32, kind: ActivityEventKind) -> ActivityEvent {
        ActivityEvent::new(network_id, node_id, kind)
    }

    #[tokio::test]
    async fn write_query_and_paginate() {
        let activity = test_activity().await;
        let events: Vec<ActivityEvent> = (0..5)
            .map(|i| {
                event(
                    0,
                    1,
                    ActivityEventKind::ActiveTipChanged {
                        old_hash: format!("{:02}", i),
                        old_height: i,
                        new_hash: format!("{:02}", i + 1),
                        new_height: i + 1,
                    },
                )
            })
            .collect();
        write_events(&activity, &events).await.expect("write");

        // Recent events come from the ring buffer, newest first.
        let recent = activity.recent_events(0, 2).await;
        assert_eq!(recent.len(), 2);
        assert_eq!(recent[0].kind, "active-tip-changed");
        assert_eq!(recent[0].details["new_height"], 5);
        assert_eq!(recent[1].details["new_height"], 4);

        // Pagination into the database with `before`.
        let page = activity
            .events_before(0, recent[1].id, 10)
            .await
            .expect("query");
        assert_eq!(page.len(), 3);
        assert_eq!(page[0].details["new_height"], 3);
        assert_eq!(page[2].details["new_height"], 1);

        // Other networks have no events.
        assert!(activity.recent_events(1, 10).await.is_empty());
        assert!(activity
            .events_before(1, i64::MAX, 10)
            .await
            .expect("query")
            .is_empty());
    }

    #[tokio::test]
    async fn ring_buffer_is_bounded_and_preloadable() {
        let activity = test_activity().await;
        let events: Vec<ActivityEvent> = (0..RING_BUFFER_SIZE + 20)
            .map(|i| {
                event(
                    0,
                    1,
                    ActivityEventKind::NodeLagging {
                        node_height: i as u64,
                        best_height: i as u64 + LAG_ENTER,
                    },
                )
            })
            .collect();
        write_events(&activity, &events).await.expect("write");

        let recent = activity.recent_events(0, RING_BUFFER_SIZE * 2).await;
        assert_eq!(recent.len(), RING_BUFFER_SIZE);
        assert_eq!(
            recent[0].details["node_height"],
            (RING_BUFFER_SIZE + 20 - 1) as u64
        );

        // Simulate a restart: clear the cache and preload from the database.
        activity.cache.lock().await.clear();
        activity.preload_cache(&[0]).await.expect("preload");
        let preloaded = activity.recent_events(0, RING_BUFFER_SIZE * 2).await;
        assert_eq!(preloaded, recent);
    }

    #[tokio::test]
    async fn archive_and_purge_moves_old_events() {
        let activity = test_activity().await;
        let now = unix_time_now();
        let mut events = vec![];
        for i in 0..10u64 {
            let mut e = event(0, 1, ActivityEventKind::NodeReachable {});
            // 5 old events (100 days ago), 5 recent ones.
            e.timestamp = if i < 5 { now - 100 * 86400 } else { now };
            events.push(e);
        }
        // An old event of another network must not be touched.
        let mut other = event(7, 1, ActivityEventKind::NodeUnreachable {});
        other.timestamp = now - 100 * 86400;
        events.push(other);
        write_events(&activity, &events).await.expect("write");

        let archive_dir = std::env::temp_dir().join(format!(
            "fork-observer-activity-archive-test-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&archive_dir);

        let cutoff = now - 90 * 86400;
        let moved = archive_and_purge(&activity.db, &archive_dir, 0, cutoff)
            .await
            .expect("archive");
        assert_eq!(moved, 5);

        // The live database only holds the recent events of network 0 plus
        // the untouched event of network 7.
        assert_eq!(
            activity
                .events_before(0, i64::MAX, 100)
                .await
                .unwrap()
                .len(),
            5
        );
        assert_eq!(
            activity
                .events_before(7, i64::MAX, 100)
                .await
                .unwrap()
                .len(),
            1
        );

        // The archive file exists, is re-queryable, and holds the 5 events.
        let archive_path = archive_dir.join(format!(
            "activity-archive-{}.sqlite",
            year_month(unix_time_now())
        ));
        let archive = Connection::open(&archive_path).expect("open archive");
        let count: i64 = archive
            .query_row("SELECT COUNT(*) FROM activity WHERE network = 0", [], |r| {
                r.get(0)
            })
            .expect("count");
        assert_eq!(count, 5);

        // A second run is a no-op and doesn't error.
        let moved = archive_and_purge(&activity.db, &archive_dir, 0, cutoff)
            .await
            .expect("archive again");
        assert_eq!(moved, 0);

        let _ = std::fs::remove_dir_all(&archive_dir);
    }

    #[test]
    fn year_month_from_unix_time() {
        assert_eq!(year_month(0), "1970-01");
        assert_eq!(year_month(1751500800), "2025-07"); // 2025-07-03
        assert_eq!(year_month(1735689599), "2024-12"); // 2024-12-31 23:59:59
        assert_eq!(year_month(1735689600), "2025-01"); // 2025-01-01 00:00:00
    }

    #[test]
    fn kind_and_details_serialization() {
        let (kind, details) = ActivityEventKind::NodeUnreachable {}.kind_and_details();
        assert_eq!(kind, "node-unreachable");
        assert_eq!(details, serde_json::json!({}));

        let (kind, details) = ActivityEventKind::TipAdded {
            hash: "aa".to_string(),
            height: 100,
            status: "valid-fork".to_string(),
        }
        .kind_and_details();
        assert_eq!(kind, "tip-added");
        assert_eq!(
            details,
            serde_json::json!({"hash": "aa", "height": 100, "status": "valid-fork"})
        );
    }
}
